### ISSUE TITLE
Existing User: Organic Organization Association

### ISSUE THREAD

**Issue by joshsager** [WaterReporter/WaterReporter-Android#18]
![screen shot 2016-01-15 at 2 30 25 pm](https://cloud.githubusercontent.com/assets/1139760/12363052/88f7a494-bb94-11e5-9469-781280c365ae.png)

**Comment by joshsager** [comment]
Sketch of the screen needed at step 5.
Also note step 6 and 7 are no longer needed

![screen shot 2016-01-15 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/1139760/12363116/eae44f9a-bb94-11e5-8f37-017272a3b10c.png)

**Comment by joshsager** [comment]
Join button should display if a user visits a report that has a group that the use has not yet joined.

If the user has joined that group then no button should display.

**Comment by joshsager** [comment]
This has been approved.

**Comment by joshsager** [comment]
The groups are not "sticking" with the submitted reports.

**Comment by brendandm** [comment]
Will be fixed through #22.
