### ISSUE TITLE
Pollution Reports need to be an Orange Pin

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/WaterReporter-Android#4]
Pollution Reports on the map need to be identified with an Orange pin using the hexcode #F9AC00

![pin-yellow-1](https://cloud.githubusercontent.com/assets/569351/5417569/cf45f962-8208-11e4-93fc-9612bd1dfd46.png)

**Comment by ryanhamley** [comment]
I had the colors set backwards in my if/else statement. Pollution reports now show up as orange. Every report coming from the API is currently a Pollution report, but it should work just fine.
