### ISSUE TITLE
Orphaned Reports not submitting to server

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/WaterReporter-Android#5]
Whenever a user clicks ( + ) to submit a new form, adds a photo and doesn't touch anything else it submits a broken report.

When you pull-to-refresh it then appears as broken.

**Comment by ryanhamley** [comment]
I made a couple of changes client-side to test for null values, but the bulk of the issue was solved server-side by inserting values for 0 in the pollution and activity types.
